name: Deploy Frontend to CF Pages

on:
  push:
    branches:
      - main
    paths:
      - 'pjsk-web/**'
  workflow_dispatch: # 新增这一行，允许手动点击运行

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          cd pjsk-web
          npm install

      - name: Build project
        run: |
          cd pjsk-web
          npm run build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: pjsk-web # 必须和你 CF 上的项目名一致
          directory: pjsk-web/dist # 编译产物路径
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}